### ISSUE TITLE
Not rendering partials

### ISSUE THREAD

**Issue by bbnnt** [railsware/smt_rails#13]
Not such a big issue, but as it is explained in your README, partials won't be rendered while using your gem with latest rails setup

Do you have a clue about it ?

**Comment by le0pard** [comment]
Maybe of using new sprokets 3? https://github.com/railsware/smt_rails/issues/12

**Comment by bbnnt** [comment]
humm, the Gemfile.lock shows 3.2.0 for sprockets

**Comment by le0pard** [comment]
Ok, so reason founded :)

**Comment by bbnnt** [comment]
You mean, "founded" ?

**Comment by le0pard** [comment]
I mean - we already have issue for this problem: https://github.com/railsware/smt_rails/issues/12 If you need to use gem right now - you can downgrade to sprockets 2 or make fix and send PR to repo (right now I don't have time to fix this)

**Comment by bbnnt** [comment]
ok thx for your reply! I'll see what can be done

**Comment by maurizi** [comment]
I'm also running into issues with rendering partials.  I'm using version `0.2.9`

**Comment by maurizi** [comment]
Update - I was able to get this to work when I switched from using `{{>path_to/partial}}` to  `{{>path_to/_partial}}` (adding a leading underscore)

**Comment by le0pard** [comment]
@maurizi thanks for info

**Comment by maurizi** [comment]
It _may_ only be when using the templates from Ruby - I haven't tried using partials from JS yet.

Great project! Awesome to be able to use the same templates on client and server.
